### ISSUE TITLE
Look at other common sitemap.xml locations

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/site-scanning-engine#183]
A number of site building tools publish sitemap files with varying names and locations. For example, at GSA we see:

[gsa.gov/sitemap-index.xml](https://www.gsa.gov/sitemap-index.xml)
[hallways.cap.gsa.gov/sitemap_index.xml](https://hallways.cap.gsa.gov/sitemap_index.xml)

The index files often link to other sitemaps which contain actual data for consumption by [buildSitemapResult](https://github.com/GSA/site-scanning-engine/blob/main/libs/core-scanner/src/pages/sitemap-xml.ts#L36). 

Checking for additional variants would help increase the accuracy of the counts provided.

**Comment by gbinal** [comment]
Hey @mvogelgesang - thanks for this issue!!  

I'm moving it over to our primary issue tracker [here](https://github.com/GSA/site-scanning/issues/283).
