### ISSUE TITLE
Add Wagtail to list of CMS's

### ISSUE THREAD

**Issue by ascott1** [GSA/site-scanning-engine#303]
[Wagtail](https://wagtail.org/) is a Python/Django-based CMS that is used by the CFPB, the FEC, the Peace Corps, NASA, HHS, and others. Would it be possible to add it to the [CMS list](https://github.com/GSA/site-scanning-engine/blob/main/libs/core-scanner/src/scans/cms.ts)? Thank you!

Tagging @gbinal

**Comment by gbinal** [comment]
thanks!  Moving this over to our main issue tracker - https://github.com/GSA/site-scanning/issues/909
